//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("www.Model", "FK_Person_Phrase", "Phrase", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(info.Models.Phrase), "Person", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(info.Models.Person), true)]

#endregion

namespace info.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Entities object using the connection string found in the 'Entities' section of the application configuration file.
        /// </summary>
        public Entities() : base("name=Entities", "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(string connectionString) : base(connectionString, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Phrase> Phrases
        {
            get
            {
                if ((_Phrases == null))
                {
                    _Phrases = base.CreateObjectSet<Phrase>("Phrases");
                }
                return _Phrases;
            }
        }
        private ObjectSet<Phrase> _Phrases;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Person> People
        {
            get
            {
                if ((_People == null))
                {
                    _People = base.CreateObjectSet<Person>("People");
                }
                return _People;
            }
        }
        private ObjectSet<Person> _People;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Watch> Watches
        {
            get
            {
                if ((_Watches == null))
                {
                    _Watches = base.CreateObjectSet<Watch>("Watches");
                }
                return _Watches;
            }
        }
        private ObjectSet<Watch> _Watches;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Phrases EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPhrases(Phrase phrase)
        {
            base.AddObject("Phrases", phrase);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the People EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPeople(Person person)
        {
            base.AddObject("People", person);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Watches EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWatches(Watch watch)
        {
            base.AddObject("Watches", watch);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="www.Model", Name="Person")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Person : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Person object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="copyID">Initial value of the CopyID property.</param>
        /// <param name="session">Initial value of the Session property.</param>
        /// <param name="leg_ID">Initial value of the Leg_ID property.</param>
        /// <param name="fullName">Initial value of the FullName property.</param>
        public static Person CreatePerson(global::System.Int32 id, global::System.Int32 copyID, global::System.Int32 session, global::System.String leg_ID, global::System.String fullName)
        {
            Person person = new Person();
            person.ID = id;
            person.CopyID = copyID;
            person.Session = session;
            person.Leg_ID = leg_ID;
            person.FullName = fullName;
            return person;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CopyID
        {
            get
            {
                return _CopyID;
            }
            set
            {
                OnCopyIDChanging(value);
                ReportPropertyChanging("CopyID");
                _CopyID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CopyID");
                OnCopyIDChanged();
            }
        }
        private global::System.Int32 _CopyID;
        partial void OnCopyIDChanging(global::System.Int32 value);
        partial void OnCopyIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Session
        {
            get
            {
                return _Session;
            }
            set
            {
                OnSessionChanging(value);
                ReportPropertyChanging("Session");
                _Session = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Session");
                OnSessionChanged();
            }
        }
        private global::System.Int32 _Session;
        partial void OnSessionChanging(global::System.Int32 value);
        partial void OnSessionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Leg_ID
        {
            get
            {
                return _Leg_ID;
            }
            set
            {
                OnLeg_IDChanging(value);
                ReportPropertyChanging("Leg_ID");
                _Leg_ID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Leg_ID");
                OnLeg_IDChanged();
            }
        }
        private global::System.String _Leg_ID;
        partial void OnLeg_IDChanging(global::System.String value);
        partial void OnLeg_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FullName
        {
            get
            {
                return _FullName;
            }
            set
            {
                OnFullNameChanging(value);
                ReportPropertyChanging("FullName");
                _FullName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FullName");
                OnFullNameChanged();
            }
        }
        private global::System.String _FullName;
        partial void OnFullNameChanging(global::System.String value);
        partial void OnFullNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("www.Model", "FK_Person_Phrase", "Phrase")]
        public Phrase Phrase
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Phrase>("www.Model.FK_Person_Phrase", "Phrase").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Phrase>("www.Model.FK_Person_Phrase", "Phrase").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Phrase> PhraseReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Phrase>("www.Model.FK_Person_Phrase", "Phrase");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Phrase>("www.Model.FK_Person_Phrase", "Phrase", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="www.Model", Name="Phrase")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Phrase : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Phrase object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="copy">Initial value of the Copy property.</param>
        public static Phrase CreatePhrase(global::System.Int32 id, global::System.String copy)
        {
            Phrase phrase = new Phrase();
            phrase.ID = id;
            phrase.Copy = copy;
            return phrase;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Copy
        {
            get
            {
                return _Copy;
            }
            set
            {
                OnCopyChanging(value);
                ReportPropertyChanging("Copy");
                _Copy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Copy");
                OnCopyChanged();
            }
        }
        private global::System.String _Copy;
        partial void OnCopyChanging(global::System.String value);
        partial void OnCopyChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("www.Model", "FK_Person_Phrase", "Person")]
        public EntityCollection<Person> People
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Person>("www.Model.FK_Person_Phrase", "Person");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Person>("www.Model.FK_Person_Phrase", "Person", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="www.Model", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="claimedIdentifier">Initial value of the ClaimedIdentifier property.</param>
        /// <param name="isAdmin">Initial value of the IsAdmin property.</param>
        public static User CreateUser(global::System.Int32 id, global::System.String claimedIdentifier, global::System.Boolean isAdmin)
        {
            User user = new User();
            user.ID = id;
            user.ClaimedIdentifier = claimedIdentifier;
            user.IsAdmin = isAdmin;
            return user;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ClaimedIdentifier
        {
            get
            {
                return _ClaimedIdentifier;
            }
            set
            {
                OnClaimedIdentifierChanging(value);
                ReportPropertyChanging("ClaimedIdentifier");
                _ClaimedIdentifier = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ClaimedIdentifier");
                OnClaimedIdentifierChanged();
            }
        }
        private global::System.String _ClaimedIdentifier;
        partial void OnClaimedIdentifierChanging(global::System.String value);
        partial void OnClaimedIdentifierChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsAdmin
        {
            get
            {
                return _IsAdmin;
            }
            set
            {
                OnIsAdminChanging(value);
                ReportPropertyChanging("IsAdmin");
                _IsAdmin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsAdmin");
                OnIsAdminChanged();
            }
        }
        private global::System.Boolean _IsAdmin;
        partial void OnIsAdminChanging(global::System.Boolean value);
        partial void OnIsAdminChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="www.Model", Name="Watch")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Watch : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Watch object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="claimedIdentifier">Initial value of the ClaimedIdentifier property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Watch CreateWatch(global::System.Int32 id, global::System.String claimedIdentifier, global::System.String name)
        {
            Watch watch = new Watch();
            watch.ID = id;
            watch.ClaimedIdentifier = claimedIdentifier;
            watch.Name = name;
            return watch;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ClaimedIdentifier
        {
            get
            {
                return _ClaimedIdentifier;
            }
            set
            {
                OnClaimedIdentifierChanging(value);
                ReportPropertyChanging("ClaimedIdentifier");
                _ClaimedIdentifier = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ClaimedIdentifier");
                OnClaimedIdentifierChanged();
            }
        }
        private global::System.String _ClaimedIdentifier;
        partial void OnClaimedIdentifierChanging(global::System.String value);
        partial void OnClaimedIdentifierChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

    
    }

    #endregion

    
}
